package com.github.mockdatagen.core

import com.intellij.database.dataSource.DatabaseConnectionManager
import com.intellij.database.dataSource.DatabaseConnectionPoint
import com.intellij.database.dataSource.LocalDataSource
import com.intellij.database.dataSource.url.JdbcUrlParserUtil
import com.intellij.database.model.DasTable
import com.intellij.database.model.ObjectKind
import com.intellij.database.psi.DbPsiFacade
import com.intellij.database.remote.jdbc.RemoteConnection
import com.intellij.database.remote.jdbc.RemotePreparedStatement
import com.intellij.database.remote.jdbc.RemoteResultSet
import com.intellij.database.util.DasUtil
import com.intellij.database.util.ObjectPath
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.project.Project
import java.sql.DatabaseMetaData
import java.sql.SQLException

/** 数据库访问:枚举数据源、获取平台远程连接、读取表/列元数据、批量插入 */
object DatabaseAccess {

    private val log = Logger.getInstance(DatabaseAccess::class.java)

    private val systemSchemas = setOf(
        "information_schema", "pg_catalog", "performance_schema", "mysql", "sys",
        "guest", "information_schema_fixed", "sysadmin", "system", "dbo_guest",
    )

    private const val CONNECT_TIMEOUT_MS = 20_000L

    data class DataSourceEntry(
        val name: String,
        val local: LocalDataSource,
        val modelTables: Map<String, DasTable>,
        val tableRefs: Map<String, TableRef>,
    )

    /** 项目内所有已配置的数据源,同时取得 DataGrip 已内省完成的表模型 */
    fun dataSourceEntries(project: Project): List<DataSourceEntry> =
        DbPsiFacade.getInstance(project).dataSources.mapNotNull { ds ->
            val local = ds.delegateDataSource as? LocalDataSource ?: return@mapNotNull null
            val collected = ArrayList<Pair<TableRef, DasTable>>()
            DasUtil.getTables(ds).forEach { table ->
                if (table.isSystem) return@forEach
                val schema = DasUtil.getSchema(table)
                if (schema != null && schema.lowercase() in systemSchemas) return@forEach
                collected.add(TableRef(schema, table.name, catalogOf(table)) to table)
            }
            // 一个数据源可以内省同一服务器上的多个数据库:此时下拉框里带上库名,
            // 否则不同库的同名表会互相覆盖,还会把表指向错误的库(插入报「关系不存在」)。
            val multiCatalog = collected.mapNotNull { it.first.catalog }.distinct().size > 1
            val tables = LinkedHashMap<String, DasTable>()
            val refs = LinkedHashMap<String, TableRef>()
            collected.forEach { (ref, table) ->
                val key = if (multiCatalog) ref.fullName else ref.displayName
                if (tables.putIfAbsent(key, table) == null) refs[key] = ref
            }
            DataSourceEntry(ds.name, local, tables, refs)
        }

    /** 表所属数据库名(PostgreSQL 即数据库,MySQL 即 schema 所在库) */
    private fun catalogOf(table: DasTable): String? {
        DasUtil.getCatalog(table)?.takeIf { it.isNotBlank() }?.let { return it }
        DasUtil.getCatalogObject(table)?.name?.takeIf { it.isNotBlank() }?.let { return it }
        val database = DasUtil.getParentOfKind(table, ObjectKind.DATABASE, true)
        return database?.name?.takeIf { it.isNotBlank() && DasUtil.getKind(database) == ObjectKind.DATABASE }
    }

    /**
     * 从 DataGrip 内省模型读取列,不经过 Remote JDBC/RMI。
     * `DasType.jdbcType` 对部分数据库类型(如 jsonb、自定义类型)返回 0,这里统一归一化,
     * 否则 0 会被当作 `setObject` 的 targetSqlType 传给驱动并报「未被支持的类型值:0」。
     */
    fun loadModelColumns(table: DasTable): List<ColumnMeta> {
        val cols = DasUtil.getColumns(table).map { column ->
            val type = column.dataType
            ColumnMeta(
                name = column.name,
                jdbcType = JdbcTypeResolver.resolve(type.jdbcType, type.typeName, type.size, type.scale),
                typeName = type.typeName,
                nullable = !column.isNotNull,
                autoIncrement = DasUtil.isAuto(column) || DasUtil.isAutoGenerated(column),
                columnSize = type.size,
                decimalDigits = type.scale,
            )
        }.toList()
        // 主键标记决定整数列用「自增序列」还是「随机整数」——随机整数会撞库中已有数据
        return PrimaryKeys.mark(cols, modelPrimaryKeyColumns(table))
    }

    /** 内省模型里的主键列名;拿不到时返回空集(真实连接读列时还会再标记一次) */
    private fun modelPrimaryKeyColumns(table: DasTable): Set<String> = runCatching {
        val key = DasUtil.getPrimaryKey(table) ?: return@runCatching emptySet()
        DasUtil.getColumns(key).map { it.name }.toSet()
    }.onFailure { log.warn("MockData: 读取内省模型主键失败 ${table.name}", it) }
        .getOrDefault(emptySet())

    /**
     * 查找控制台会话的活动远程连接;数据源内省连接通常不在此列表。
     * 目标表有明确所属库时,只复用「当前库一致」的连接,避免把数据插进错误的数据库。
     */
    private fun findActiveConnection(ds: LocalDataSource, catalog: String?): RemoteConnection? =
        DatabaseConnectionManager.getInstance().activeConnections.firstOrNull { conn ->
            val point = conn.connectionPoint
            val sameDs = point === ds || point.dataSource === ds || point.dataSource?.name == ds.name
            if (!sameDs) return@firstOrNull false
            if (catalog.isNullOrBlank()) return@firstOrNull true
            val current = runCatching { conn.remoteConnection?.catalog }.getOrNull()
            current.isNullOrBlank() || current.equals(catalog, ignoreCase = true)
        }?.remoteConnection

    private fun probe(conn: RemoteConnection): Boolean = try {
        conn.isValid(10)
    } catch (_: Exception) {
        false
    }

    /**
     * 把连接点绑定到目标表所在的数据库。
     *
     * 优先用平台自带的 `JdbcUrlParserUtil.connectedTo(点, 对象路径)`:它会按驱动声明的
     * `boundTo`(PostgreSQL 为 DATABASE)去改写 URL 里对应参数,是 DataGrip 自己切换数据库的方式。
     * 平台返回 null 时退回自行改写 URL(仅当能确定当前库名且与目标不同才会改写)。
     */
    private fun pointFor(ds: LocalDataSource, table: TableRef?): DatabaseConnectionPoint {
        val catalog = table?.catalog?.takeIf { it.isNotBlank() } ?: return ds
        if (JdbcUrlUtil.databaseOf(ds.url)?.equals(catalog, ignoreCase = true) == true) return ds

        val rebound = runCatching {
            var path = ObjectPath.ROOT.append(catalog, ObjectKind.DATABASE)
            table.schema?.takeIf { it.isNotBlank() }?.let { path = path.append(it, ObjectKind.SCHEMA) }
            path = path.append(table.name, ObjectKind.TABLE)
            JdbcUrlParserUtil.connectedTo(ds as DatabaseConnectionPoint, path)
        }.onFailure { log.warn("MockData: connectedTo 失败,改用 URL 改写", it) }.getOrNull()

        // 平台重绑成功时返回的是新的连接点(Adapter 子类);无法重绑时会原样返回入参,
        // 所以用引用比较判断,不能只看 URL——部分驱动把库名放在连接属性里,URL 不变。
        if (rebound != null && rebound !== ds) {
            log.info("MockData: 连接点已绑定到数据库 [$catalog] -> ${redactUrl(rebound.url)}")
            return rebound
        }

        val rewritten = JdbcUrlUtil.withDatabase(ds.url, catalog)
        if (rewritten != null) {
            log.info("MockData: 连接 URL 改写为数据库 [$catalog] -> $rewritten")
            return object : DatabaseConnectionPoint.Adapter(ds as DatabaseConnectionPoint) {
                override fun getUrl(): String = rewritten
            }
        }

        log.warn("MockData: 无法把连接绑定到数据库 [$catalog],沿用原 URL: ${redactUrl(ds.url)}")
        return ds
    }

    /** 建一次性平台连接;超时/失败时给出可读信息 */
    private fun openConnection(project: Project, ds: LocalDataSource, point: DatabaseConnectionPoint): com.intellij.database.util.GuardedRef<com.intellij.database.dataSource.DatabaseConnection> {
        val builder = DatabaseConnectionManager.getInstance().build(project, point)
        val future = java.util.concurrent.CompletableFuture.supplyAsync {
            builder.createBlockingNonCancellable()
        }
        return try {
            future.get(CONNECT_TIMEOUT_MS, java.util.concurrent.TimeUnit.MILLISECONDS)
                ?: throw SQLException("平台为数据源「${ds.name}」返回了空连接")
        } catch (e: java.util.concurrent.TimeoutException) {
            future.cancel(true)
            throw SQLException(
                "连接数据源「${ds.name}」超时(${CONNECT_TIMEOUT_MS / 1000} 秒)。" +
                    "请确认数据库可达,且在 DataGrip 中能正常连接。",
                e,
            )
        } catch (e: java.util.concurrent.ExecutionException) {
            throw (e.cause as? Exception ?: e)
        }
    }

    /**
     * DataGrip 2026.2 的 DatabaseConnection 暴露 RemoteConnection,不能强转 java.sql.Connection。
     * 优先复用活动远程连接;没有时按目标表所属数据库创建一次性平台连接(用完释放)。
     */
    fun <T> withConnection(
        project: Project,
        ds: LocalDataSource,
        table: TableRef? = null,
        forceNew: Boolean = false,
        action: (RemoteConnection) -> T,
    ): T {
        val catalog = table?.catalog?.takeIf { it.isNotBlank() }
        val reused = if (forceNew) null else findActiveConnection(ds, catalog)
        if (reused != null && probe(reused)) return action(reused)

        val point = pointFor(ds, table)
        val guarded = try {
            openConnection(project, ds, point)
        } catch (e: Exception) {
            if (point === ds) throw e
            // 绑定到目标库失败时不静默退化:先按原 URL 连上,后续会校验库名并给出明确提示
            log.warn("MockData: 绑定数据库 [$catalog] 的连接建立失败,回退到数据源默认连接", e)
            openConnection(project, ds, ds)
        }
        return try {
            val connection = guarded.get()
                ?: throw SQLException("平台为数据源「${ds.name}」返回了空 DatabaseConnection")
            val remote = connection.remoteConnection
                ?: throw SQLException("平台连接「${ds.name}」没有 RemoteConnection")
            action(remote)
        } finally {
            // DataGrip 的连接释放可能等待内部数据源同步,不能阻塞加载结果返回和 Swing UI 更新
            Thread({ runCatching { guarded.close() } }, "mockdatagen-release-connection").apply {
                isDaemon = true
                start()
            }
        }
    }

    /** 加载所有用户表 */
    fun loadTables(conn: RemoteConnection): List<TableRef> {
        val refs = ArrayList<TableRef>()
        val catalog = runCatching { conn.catalog }.getOrNull()
        val rs = conn.metaData.getTables(null, null, "%", arrayOf("TABLE"))
        try {
            while (rs.next()) {
                val schema = rs.getString("TABLE_SCHEM")
                val name = rs.getString("TABLE_NAME")
                if (schema != null && schema.lowercase() in systemSchemas) continue
                if (name != null) refs.add(TableRef(schema, name, catalog))
            }
        } finally {
            runCatching { rs.close() }
        }
        return refs.sortedBy { it.displayName }
    }

    /**
     * 读取指定表的列元数据。
     *
     * 同时用 JDBC 元数据标记主键 / 单列唯一列:`DasType.jdbcType` 之类的类型信息与
     * "这一列的值必须唯一"是两件事,而规则推断需要后者(整数主键必须用自增序列,
     * 用随机整数会撞库中已有数据)。
     */
    fun loadColumns(conn: RemoteConnection, table: TableRef): List<ColumnMeta> {
        val cols = ArrayList<ColumnMeta>()
        val rs = conn.metaData.getColumns(null, table.schema, table.name, "%")
        try {
            while (rs.next()) {
                val columnName = rs.getString("COLUMN_NAME") ?: continue
                val typeName = rs.getString("TYPE_NAME") ?: "?"
                cols.add(
                    ColumnMeta(
                        name = columnName,
                        jdbcType = JdbcTypeResolver.resolve(rs.getInt("DATA_TYPE"), typeName),
                        typeName = typeName,
                        nullable = rs.getInt("NULLABLE") != DatabaseMetaData.columnNoNulls,
                        autoIncrement = isAutoIncrement(rs),
                        columnSize = rs.getInt("COLUMN_SIZE"),
                        decimalDigits = rs.getInt("DECIMAL_DIGITS"),
                    ),
                )
            }
        } finally {
            runCatching { rs.close() }
        }
        // 驱动元数据对"主键/自增"并不可靠(DataGrip 的远程元数据在 PG 上会静默返回空且不抛异常),
        // 所以再直查一次 information_schema,两边取并集 —— 任何一方认出来都算。
        val sql = sqlStructure(conn, table)
        val jdbcPk = primaryKeyColumns(conn, table)
        val jdbcUnique = uniqueColumns(conn, table)
        val jdbcAuto = cols.filter { it.autoIncrement }.map { it.name }
        log.info(
            "MockData: 结构探测 ${table.fullName} -> " +
                "JDBC[主键=[${jdbcPk.joinToString(",")}] 单列唯一=[${jdbcUnique.joinToString(",")}] " +
                "自增=[${jdbcAuto.joinToString(",")}]] SQL[${sql.describe()}]",
        )
        if (jdbcPk.isEmpty() && jdbcUnique.isEmpty() && jdbcAuto.isEmpty() && sql.isEmpty) {
            log.warn("MockData: 未能探测到任何主键/唯一/自增信息 ${table.fullName},唯一列将依赖插入失败后的自动修复")
        }
        return PrimaryKeys.mark(
            cols,
            jdbcPk + sql.primaryKeys,
            jdbcUnique + sql.uniqueColumns,
            sql.autoColumns,
        )
    }

    /** 直查 information_schema 拿主键 / 单列唯一 / 自增列(原因见 [StructureSql] 类注释) */
    private fun sqlStructure(conn: RemoteConnection, table: TableRef): StructureSql.Structure = runCatching {
        // 表名 / schema 走参数绑定(见 StructureSql.Sql),不拼进 SQL 字符串
        val constraintQuery = StructureSql.constraintSql(table.schema, table.name)
        val constraints = queryRows(conn, constraintQuery.text, constraintQuery.params) { rs ->
            StructureSql.ConstraintRow(
                rs.getString("constraint_type").orEmpty(),
                rs.getString("constraint_name").orEmpty(),
                rs.getString("column_name").orEmpty(),
            )
        }
        val columnQuery = StructureSql.columnSql(table.schema, table.name)
        val columns = queryRows(conn, columnQuery.text, columnQuery.params) { rs ->
            StructureSql.ColumnRow(
                name = rs.getString("column_name").orEmpty(),
                isIdentity = rs.getString("is_identity").equals("YES", ignoreCase = true),
                columnDefault = rs.getString("column_default"),
            )
        }
        var structure = StructureSql.fromConstraints(constraints) + StructureSql.fromColumns(columns)
        // MySQL 的自增在 extra 列上,其他数据库没有该列,按产品名判断后再查
        val product = runCatching { conn.metaData.databaseProductName }.getOrNull()
        if (StructureSql.isMysql(product)) {
            val autoQuery = StructureSql.mysqlAutoSql(table.schema, table.name)
            val auto = queryRows(conn, autoQuery.text, autoQuery.params) { rs ->
                rs.getString("column_name").orEmpty()
            }
            structure += StructureSql.Structure(autoColumns = auto.toSet())
        }
        structure
    }.onFailure {
        log.warn("MockData: SQL 结构探测失败 ${table.fullName},退回驱动元数据", it)
    }.getOrDefault(StructureSql.Structure())

    /**
     * 执行带**绑定参数**的查询并按行映射,语句与结果集用完即关。
     *
     * 表名、schema 这类外部数据一律用 `?` 绑定,不做字符串拼接 ——
     * 拼接要靠转义规则兜住所有数据库(MySQL 的 `\`、标准 SQL 的 `'`),漏一种就是注入。
     */
    private fun <T> queryRows(
        conn: RemoteConnection,
        sql: String,
        params: List<String>,
        map: (RemoteResultSet) -> T,
    ): List<T> {
        val ps = conn.prepareStatement(sql)
        try {
            params.forEachIndexed { i, p -> ps.setString(i + 1, p) }
            val rs = ps.executeQuery()
            try {
                val rows = ArrayList<T>()
                while (rs.next()) rows.add(map(rs))
                return rows
            } finally {
                runCatching { rs.close() }
            }
        } finally {
            runCatching { ps.close() }
        }
    }

    /** 主键列名(JDBC 元数据);失败不影响插入,只让规则退化为按列名/类型推断 */
    private fun primaryKeyColumns(conn: RemoteConnection, table: TableRef): Set<String> = runCatching {
        val names = LinkedHashSet<String>()
        val rs = conn.metaData.getPrimaryKeys(null, table.schema, table.name)
        try {
            while (rs.next()) rs.getString("COLUMN_NAME")?.let { names.add(it) }
        } finally {
            runCatching { rs.close() }
        }
        names
    }.onFailure { log.warn("MockData: 读取主键失败 ${table.fullName}", it) }.getOrDefault(emptySet())

    /**
     * 单列唯一约束的列名。多列联合唯一无法靠单列取值保证,这里直接忽略 ——
     * 误标会让界面给出误导性的自动规则。
     */
    private fun uniqueColumns(conn: RemoteConnection, table: TableRef): Set<String> = runCatching {
        val byIndex = LinkedHashMap<String, MutableList<String>>()
        val rs = conn.metaData.getIndexInfo(null, table.schema, table.name, true, true)
        try {
            while (rs.next()) {
                if (rs.getBoolean("NON_UNIQUE")) continue
                val column = rs.getString("COLUMN_NAME") ?: continue
                byIndex.getOrPut(rs.getString("INDEX_NAME") ?: column) { ArrayList() }.add(column)
            }
        } finally {
            runCatching { rs.close() }
        }
        byIndex.values.filter { it.size == 1 }.map { it[0] }.toSet()
    }.onFailure { log.warn("MockData: 读取唯一约束失败 ${table.fullName}", it) }.getOrDefault(emptySet())

    /**
     * RemoteResultSet 是 DataGrip 的短生命周期 RMI 对象,连接切换或平台回收时可能抛 NoSuchObjectException。
     * 列信息按表懒加载,失败后使用全新平台连接重试一次,避免复用已失效的远程对象。
     */
    fun loadColumnsWithRetry(project: Project, ds: LocalDataSource, table: TableRef): List<ColumnMeta> {
        var firstFailure: Throwable? = null
        repeat(2) { attempt ->
            try {
                return withConnection(project, ds, table, forceNew = attempt > 0) { conn ->
                    loadColumns(conn, table)
                }
            } catch (e: Throwable) {
                if (attempt == 0 && isStaleRemoteObject(e)) {
                    firstFailure = e
                } else {
                    firstFailure?.let { e.addSuppressed(it) }
                    throw e
                }
            }
        }
        throw firstFailure ?: SQLException("读取表「${table.displayName}」列信息失败")
    }

    /**
     * 从真实数据库连接读取列结构 —— 列的权威来源。
     *
     * DataGrip 的内省模型(`DasUtil.getColumns`)可能落后于数据库实际结构(表被 ALTER 加列后
     * 未重新内省),而插入走的是真实连接:两边不一致时,界面少掉的 NOT NULL 列不会被生成,
     * 整批插入会以 "violates not-null constraint" 失败。所以展示与插入必须用同一份列。
     */
    fun liveColumns(project: Project, ds: LocalDataSource, table: TableRef): List<ColumnMeta> {
        val cols = loadColumnsWithRetry(project, ds, table)
        log.info(
            "MockData: 数据库实际列 ${table.fullName} -> ${cols.size} 列 " +
                cols.joinToString(", ") { "${it.name}:${it.typeName}" },
        )
        return cols
    }

    private fun isStaleRemoteObject(error: Throwable): Boolean {
        var current: Throwable? = error
        while (current != null) {
            if (current is java.rmi.NoSuchObjectException) return true
            current = current.cause
        }
        return false
    }

    private fun isAutoIncrement(rs: RemoteResultSet): Boolean = try {
        rs.getString("IS_AUTOINCREMENT")?.equals("YES", true) ?: false
    } catch (_: Exception) {
        false
    }

    /**
     * 生成插入 SQL,标识符按数据库规则加引号。
     * @param rawExpressions 列名 -> 原样输出的 SQL 表达式(如 now()),这些列不使用 ? 占位符
     */
    fun buildInsertSql(
        conn: RemoteConnection,
        table: TableRef,
        columns: List<ColumnMeta>,
        rawExpressions: Map<String, String> = emptyMap(),
    ): String {
        val q = identifierQuote(conn)
        val tableIdent = qualifiedName(table, q)
        val cols = columns.joinToString(", ") { q + it.name.replace(q, q + q) + q }
        val marks = columns.joinToString(", ") { c -> rawExpressions[c.name] ?: "?" }
        return "INSERT INTO $tableIdent ($cols) VALUES ($marks)"
    }

    /**
     * 批量插入,忽略 disabled / SKIP 的列。
     *
     * @param onNotice 自动调整(如唯一冲突后改列生成方式)的通知,由调用方展示给用户
     */
    fun insertRows(
        project: Project,
        ds: LocalDataSource,
        table: TableRef,
        rules: List<RuleConfig>,
        rowCount: Int,
        indicator: ProgressIndicator?,
        onProgress: (done: Int) -> Unit = {},
        onNotice: (String) -> Unit = {},
    ): Int {
        val generator = MockDataGenerator()
        var inserted = 0

        withConnection(project, ds, table) { conn ->
            val connCatalog = runCatching { conn.catalog }.getOrNull()
            // 表和连接不在同一个库时必然失败(且可能是插错库),提前给出可操作的信息
            val target = table.catalog
            if (!target.isNullOrBlank() && !connCatalog.isNullOrBlank() &&
                !target.equals(connCatalog, ignoreCase = true)
            ) {
                throw SQLException(
                    "表 ${table.fullName} 属于数据库「$target」,但当前连接落在「$connCatalog」。" +
                        "请在数据源设置里把 URL 指向该库(或在数据库窗口中打开该库的控制台连接)后重试。",
                )
            }

            // 自增列的起始值必须按库中实际最大值解析:否则会与已有数据重复
            // (PostgreSQL 报「重复键违反唯一约束 xxx_pkey」,MySQL 报 Duplicate entry)
            val effectiveRules = resolveAutoStarts(conn, table, rules)
            // 被判定为"数据库自己生成"而从 INSERT 中移除的列(自动修复的结果)
            val dropped = LinkedHashSet<String>()
            var attemptRules = effectiveRules.filter { it.enabled && it.type != RuleType.SKIP }
            var attempt = 0

            while (true) {
                // 「数据库表达式」列直接内联到 SQL,不参与参数绑定
                val rawExpressions = attemptRules
                    .filter { it.type == RuleType.SQL_EXPRESSION }
                    .associate { it.column.name to it.param.trim() }
                    .filterValues { it.isNotEmpty() }

                val sql = buildInsertSql(conn, table, attemptRules.map { it.column }, rawExpressions)
                // 取值必须用「本次尝试实际生效的规则」:自动修复改过的列(冲突列改成自增数字)
                // 如果仍按最初的规则生成,绑定阶段拿到的还是旧值(如撞库的随机整数)
                val genRules = RuleRepairs.withActive(effectiveRules, attemptRules)
                val oldAutoCommit = conn.autoCommit
                conn.autoCommit = false
                try {
                    val ps = conn.prepareStatement(sql)
                    var attemptInserted = 0
                    try {
                        val chunk = 500
                        for (i in 0 until rowCount) {
                            val row = generator.generateRow(genRules, i.toLong())
                            var idx = 1
                            for (r in attemptRules) {
                                if (rawExpressions.containsKey(r.column.name)) continue
                                bindParam(ps, idx, row[r.column.name], r.column, i)
                                idx++
                            }
                            ps.addBatch()
                            if ((i + 1) % chunk == 0 || i == rowCount - 1) {
                                attemptInserted += ps.executeBatch().sum()
                            }
                            if (i % 500 == 0) onProgress(i)
                            indicator?.checkCanceled()
                        }
                    } finally {
                        runCatching { ps.close() }
                    }
                    conn.commit()
                    inserted = attemptInserted
                    break
                } catch (e: Exception) {
                    // 整批回滚:先前 executeBatch 成功的分片也一起退掉,计数必须归零
                    runCatching { conn.rollback() }
                    if (e is SQLException && e.message?.startsWith("表 ") == true) throw e
                    // 唯一约束冲突只自动修一次:改掉冲突列的生成方式后重跑整批
                    val repaired = if (attempt == 0) {
                        autoRepairConflict(conn, table, InsertFailure.text(e), attemptRules, dropped, onNotice)
                    } else {
                        null
                    }
                    if (repaired == null) throw insertFailed(e, table, connCatalog)
                    attemptRules = repaired
                    attempt++
                } finally {
                    runCatching { conn.autoCommit = oldAutoCommit }
                }
            }
        }
        return inserted
    }

    /**
     * 唯一约束冲突的自动修复(只试一次)。
     *
     * 主键/唯一列的取值必须互不相同,可"这一列必须唯一"未必探测得到(驱动元数据可能静默失败,
     * 见 [sqlStructure])。与其把数据库原文抛给用户,不如按冲突列直接改掉生成方式再试一遍:
     *  - 该列由数据库自己生成(serial / identity / auto_increment)→ 从 INSERT 中移除,交给数据库;
     *  - 否则是整数列 → 改成「自增数字」,从库中最大值 + 1 开始接续。
     * 两种情况都不适用时返回 null,由调用方抛出带可操作提示的异常。
     */
    private fun autoRepairConflict(
        conn: RemoteConnection,
        table: TableRef,
        errorText: String,
        rules: List<RuleConfig>,
        dropped: MutableSet<String>,
        onNotice: (String) -> Unit,
    ): List<RuleConfig>? {
        val column = InsertFailure.conflictColumn(errorText) ?: return null
        if (!RuleRepairs.contains(rules, column)) return null

        val dbGenerated = runCatching {
            sqlStructure(conn, table).autoColumns.any { it.equals(column, ignoreCase = true) }
        }.getOrDefault(false)
        if (dbGenerated) {
            dropped.add(column)
            val notice = "列「$column」由数据库自动生成,已从插入语句中移除(交给数据库赋值)"
            log.warn("MockData: $notice")
            onNotice(notice)
            return rules.filterNot { r -> dropped.any { it.equals(r.column.name, ignoreCase = true) } }
        }

        if (!RuleRepairs.canContinue(rules, column)) return null
        val start = (runCatching { maxValue(conn, table, column) }.getOrNull() ?: 0L) + 1
        val notice = "列「$column」与库中已有数据重复,已自动改为「自增数字」并从 $start 开始接续"
        log.warn("MockData: $notice")
        onNotice(notice)
        return RuleRepairs.continueFrom(rules, column, start)
    }

    /** 统一的插入失败异常:附上可操作提示(NOT NULL / 唯一约束) */
    private fun insertFailed(e: Exception, table: TableRef, connCatalog: String?): SQLException {
        val hint = InsertFailure.hint(InsertFailure.text(e))
        return SQLException(
            buildString {
                append("向表 ${table.fullName} 插入失败(连接数据库:${connCatalog ?: "未知"}):${e.message}")
                if (hint != null) append("\n").append(hint)
            },
            e,
        )
    }

    /**
     * 把「起始值 = auto」的自增列解析成"库中该列最大值 + 1"。
     *
     * 为什么必须在插入前解析:自增列(尤其是主键)的值必须唯一,而界面上的参数是静态的 ——
     * 若固定从 1 开始,库里已有数据时整批插入都会以唯一约束冲突失败。这里用真实连接取
     * 当前最大值并接续,既保证唯一又保持递增语义。
     */
    private fun resolveAutoStarts(
        conn: RemoteConnection,
        table: TableRef,
        rules: List<RuleConfig>,
    ): List<RuleConfig> {
        val targets = rules.filter {
            it.enabled && it.type == RuleType.AUTO_INCREMENT &&
                isAutoStartValue(RuleParamSpec.parse(it.type, it.param).firstOrNull().orEmpty())
        }
        if (targets.isEmpty()) return rules

        val starts = HashMap<String, Long>()
        for (r in targets) {
            val max = runCatching { maxValue(conn, table, r.column.name) }
                .onFailure { log.warn("MockData: 读取 ${table.fullName}.${r.column.name} 最大值失败", it) }
                .getOrNull()
            starts[r.column.name] = (max ?: 0L) + 1
        }
        log.info("MockData: 自增起始值 ${table.fullName} -> " + starts.entries.joinToString { "${it.key}=${it.value}" })

        return rules.map { r ->
            val start = starts[r.column.name] ?: return@map r
            val parts = RuleParamSpec.parse(r.type, r.param).toMutableList()
            if (parts.isEmpty()) parts.add(start.toString()) else parts[0] = start.toString()
            r.copy(param = RuleParamSpec.compose(r.type, parts))
        }
    }

    /** 表内某列的最大值;空表或全为 NULL 时返回 null */
    private fun maxValue(conn: RemoteConnection, table: TableRef, column: String): Long? {
        val q = identifierQuote(conn)
        val colIdent = q + column.replace(q, q + q) + q
        val st = conn.createStatement()
        try {
            val rs = st.executeQuery("SELECT MAX($colIdent) FROM ${qualifiedName(table, q)}")
            try {
                if (!rs.next()) return null
                val value = rs.getLong(1)
                return if (rs.wasNull()) null else value
            } finally {
                runCatching { rs.close() }
            }
        } finally {
            runCatching { st.close() }
        }
    }

    /**
     * 各数据库的标识符引号。
     *
     * 只接受 1~2 个字符的引号(如 `"` 或 `` ` ``):JDBC 规定"不支持的驱动返回一个空格",
     * 把空格当引号用会生成 ` col ` 这种既非合法引用、也失去保护的 SQL,退回 ANSI 双引号更稳。
     */
    private fun identifierQuote(conn: RemoteConnection): String = try {
        val raw = conn.metaData.identifierQuoteString?.trim()
        if (raw.isNullOrBlank() || raw.length > 2) "\"" else raw
    } catch (_: Exception) {
        "\""
    }

    /**
     * 日志里的 JDBC URL 脱敏。
     *
     * URL 可能带 `?user=..&password=..` 这类凭据参数(部分驱动支持),而日志常被用户
     * 直接贴进工单或 issue —— 落到日志里的凭据等同于泄露。
     */
    private fun redactUrl(url: String?): String = url
        ?.replace(Regex("(?i)(password|passwd|pwd|secret|token|apikey)=([^&;\\s]*)"), "$1=***")
        ?: "null"

    private fun qualifiedName(table: TableRef, q: String): String = buildString {
        if (!table.schema.isNullOrBlank()) append(q + table.schema.replace(q, q + q) + q + ".")
        append(q + table.name.replace(q, q + q) + q)
    }

    /**
     * 绑定单个参数。
     *
     * `targetSqlType` 必须先归一化:驱动的 `setObject(i, value, targetType)` 只接受固定的类型常量
     * 白名单,传入 0(即 `Types.NULL`,DataGrip 对部分类型会给出 0)或
     * `NVARCHAR(-9)`/`NCHAR(-15)`/`NCLOB(2011)` 之类都会被驱动拒绝
     * (PostgreSQL 报「未被支持的类型值:0」)。归一化后仍不确定的类型,退回两参 `setObject`,
     * 由驱动/数据库自行推断。
     */
    private fun bindParam(
        ps: RemotePreparedStatement,
        idx: Int,
        value: Any?,
        column: ColumnMeta,
        rowIndex: Int,
    ) {
        val target = JdbcTypeResolver.resolve(
            column.jdbcType,
            column.typeName,
            column.columnSize,
            column.decimalDigits,
        )
        try {
            when {
                value == null && JdbcTypeResolver.isBindableTarget(target) -> ps.setNull(idx, target)
                value == null -> ps.setObject(idx, null)
                JdbcTypeResolver.isBindableTarget(target) -> ps.setObject(idx, value, target)
                else -> ps.setObject(idx, value)
            }
        } catch (e: SQLException) {
            throw SQLException(
                "列 [${column.name}](${column.typeName}) 第 ${rowIndex + 1} 行参数绑定失败:${e.message}",
                e,
            )
        }
    }

}
